### ISSUE TITLE
AS A system administrator I WANT a key list that includes RSA key files from the SSH directory in my home directory IN ORDER TO understand what keys I have available

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#2]
**Acceptance criteria**

All the below acceptance criteria are specific to the `$HOME/.ssh` directory, and that is what is referred to when talking about the directory below. 

- [x] A window should be displayed
- [x] If there are no ssh RSA keys in the folder then a message should be displayed
- [x] If there are, an entry for each RSA key pair or public/private key without corresponding pair should appear on the list
- [x] A scroll bar should appear in order to scroll over the list only if there are too many keys to display
- [x] If the user has no .ssh directory in its home directory, the application should behave as if the .ssh directory existed but was empty
- [x] If the program can't read the .ssh directory, the application should behave as if the .ssh directory existed but was empty and log a message in the log
- [x] If there is a file in the .ssh directory that doesn't contain an actual RSA key, then we don't display that file on the list
- [x] If a file does not follow the naming convention but does contain an RSA key, then we display it
- [x] If two files follow the naming convention (for example: `id_rsa` and `id_rsa.pub`) we will display them as one entry on the list; we will not verify if they match
- [x] If two files do not follow the naming convention (for example: `id_rsa` and `id_rsa_other.pub`) but they match, they will be displayed as two separate items on the list
- [x] No distinction will be made on the list between public or private keys
- [x] No indication that they are RSA keys, only thing on the list will be name of the file
- [x] We should output useful information for each operation in the story for debugging purposes 
- [x] This story will NOT cover de-duplication (if a public or private key is found in more than one place, they will be shown as separate entries in the key list)
- [x] When displaying a key entry for a key pair, only the path to the PRIVATE key will be displayed.

**Comment by olabiniV2** [comment]
Initial task list:

- [ ] Start the UI from the main function
- [ ] Wire up gotk3adapter etc
- [ ] Wire up the logging library
- [ ] Wire up i18n
- [ ] Create a main window
- [ ] Wire up an SSH library for understanding RSA keys (prefer pure-golang, maybe x/crypto)
- [ ] Create a scrollbar wrapper
- [ ] Create an element for each key
- [ ] Set up test framework and start testing
- [ ] Create a package for reading SSH directory
- [ ] Create a package for managing RSA keys

**Comment by piratax007** [comment]
After reviewing acceptance criteria, this story is declared as done.
