### ISSUE TITLE
AS A system administrator I WANT TO be able to load key details about an SSH public key on my system IN ORDER TO understand the key better even without the private key

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#38]
**Acceptance criteria**

- [x] When a public key in the key list is clicked and no key details are being detailed, a segment of the window will open up and show key details for that key - this segment of the window will be called the key details component in the rest of these criteria.
- [x] When a key pair in the key list is clicked, the key details component will remove what was previously shown, and instead display information about the public key from the clicked key pair
- [x] The key details component when displayed, can be closed in some way such that no key details are shown anymore
- [x] In this story, the only information that will be displayed in the key details component is the PATH of the public key
- [x] If a private key is clicked in the key list, the current information in the key details component will be removed, if the component is visible. If the component is not visible, nothing will happen.
- [x] The key list should highlight in some way which key entry is currently being displayed in the key details component.
- [x] If the path of the public key is too long to fit in the current size of the component, the FRONT of the path (the root component) should be truncated to fit, and a ellipsis be inserted in front to indicate the removed parts. For example, if you have the path "/home/someonewithalong/ssh/path/to/their/home/.ssh/github.pub", could be truncated to "...ath/to/their/home/.ssh/github.pub". In the case of truncation, you should be able to hover over the path and the full path will be displayed in a tooltip of some kind.
- [x] If the window is resized, any decision about truncation should be recalculated
- [x] The path should be displayed properly even if it contains "strange" characters, spaces or other unicode code points.
- [ ] TODO: create new story for this behavior: The component should have a button in one corner, with some kind of symbol with two arrows maybe, that when you press it will expand the window to a sufficient size to display the information inside it, with reasonable limits (it shouldn't expand to be larger than the display size of the desktop, for example)
- [ ] TODO: create new story for adding a button or way of opening of the folder containing the public key in Nautilius or whatever file explorer the user has

**Comment by piratax007** [comment]
All functionality has been completed for this story, and all acceptance criteria have been met.
