### ISSUE TITLE
AS A system administrator I WANT TO be able to load key details about an SSH private key on my system IN ORDER TO understand the key better even without the public key

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#39]
Acceptance criteria:

- [x] When pressing a private key in the key list, the path for the private key should be displayed in the key details window
- [x] The path should follow the same requirements as those used for displaying the public key path
- [x] When a public key is pressed, no information about a private key will be visible
- [x] The key detail window should indicate in some way that you are viewing a private key instead of a public key, apart from the path
