### ISSUE TITLE
AS A system administrator I WANT TO be able to see key details about a password protected key IN ORDER TO fully understand the key I'm working on

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#48]
Acceptance criteria:
- [x] A password protected ed25519 or RSA private key should still show up in the key list, with the same appearance as a non-protected private key
- [x] A password protected ed25519 or RSA private key should also still show up in the key list as part of a key pair with no difference in appearance
- [x] When showing the key details for a password protected private key, or a key entry containing a password protected key, the component should indicate somewhere in the key details window that the private key Is password protected
- [x] For now, we do not need to manage passwords or open up the private key material. This should be revisited in the first story that uses private key material for something.
