### ISSUE TITLE
AS A system administrator I WANT TO see a hash of the public key using SHA-1 displayed in hexadecimal separated with colons IN ORDER TO compare against fingerprints on other systems

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#54]
*Acceptance criteria*
- [x] The key details component should always show the SHA-1 hash for a public key or a key pair.
- [x] The hash is composed of 160 bits (20 bytes). These should be displayed in hexadecimal, with capital letters, separated by colons
- [x] If a private key is displayed, nothing should be shown
- [x] The hash should be possible to select and copy
- [x] The hashing over the public key should be done using the "normal" fingerprint generation for that key algorithm. Exactly what that means will be different for different algorithms. But, for SSH keys, for example, the SHA-1 fingerprint we display should be the same as what the SSH tool would display.
